services:
  app:
    build: .
    environment:
      - ENV=docker
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_NAME=binance
      - DB_USER=postgres
      - DB_PASSWORD=postgres
      - DB_SSLMODE=disable
      - MIGRATIONS_PATH=/app/migrations
      - GRPC_PORT=50051
      - BINANCE_API_URL=https://api.binance.com/api/v3/depth?symbol=BTCUSDT&limit=1
      - METRICS_PORT=2112
      - OTLP_ENDPOINT=jaeger:4318
    ports:
      - "50051:50051"
      - "2112:2112"
    healthcheck:
      test: ["CMD-SHELL", "wget -q -O - http://localhost:2112/metrics || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 3
    depends_on:
      postgres:
        condition: service_healthy
      jaeger:
        condition: service_healthy

  postgres:
    image: postgres:14
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=binance
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d binance"]
      interval: 5s
      timeout: 5s
      retries: 5

  jaeger:
    image: jaegertracing/all-in-one:1.42
    environment:
      - COLLECTOR_OTLP_ENABLED=true
    ports:
      - "14268:14268"  # HTTP collector
      - "16686:16686"  # Web UI
      - "4317:4317"    # OTLP gRPC
      - "4318:4318"    # OTLP HTTP
    healthcheck:
      test: [ "CMD", "wget", "-q", "--spider", "http://localhost:16686/" ]
      interval: 5s
      timeout: 5s
      retries: 10
      start_period: 10s

  prometheus:
    image: prom/prometheus:v2.40.0
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "9091:9090"
    depends_on:
      app:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "wget", "--spider", "http://localhost:9090/-/healthy"]
      interval: 10s
      timeout: 2s
      retries: 5