//

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.35.1
// 	protoc        v3.21.12
// source: usdt.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetRateFromExchangeRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *GetRateFromExchangeRequest) Reset() {
	*x = GetRateFromExchangeRequest{}
	mi := &file_usdt_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetRateFromExchangeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetRateFromExchangeRequest) ProtoMessage() {}

func (x *GetRateFromExchangeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_usdt_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetRateFromExchangeRequest.ProtoReflect.Descriptor instead.
func (*GetRateFromExchangeRequest) Descriptor() ([]byte, []int) {
	return file_usdt_proto_rawDescGZIP(), []int{0}
}

type GetRateFromExchangeResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Success   bool    `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`                       // Успех операции сохранения
	Ask       float32 `protobuf:"fixed32,2,opt,name=ask,proto3" json:"ask,omitempty"`                              // Цена ask
	Bid       float32 `protobuf:"fixed32,3,opt,name=bid,proto3" json:"bid,omitempty"`                              // Цена bid
	AskAmount float32 `protobuf:"fixed32,4,opt,name=ask_amount,json=askAmount,proto3" json:"ask_amount,omitempty"` // Объем по цене ask
	BidAmount float32 `protobuf:"fixed32,5,opt,name=bid_amount,json=bidAmount,proto3" json:"bid_amount,omitempty"` // Объем по цене bid
	Timestamp string  `protobuf:"bytes,6,opt,name=timestamp,proto3" json:"timestamp,omitempty"`                    // Время получения курса
}

func (x *GetRateFromExchangeResponse) Reset() {
	*x = GetRateFromExchangeResponse{}
	mi := &file_usdt_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetRateFromExchangeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetRateFromExchangeResponse) ProtoMessage() {}

func (x *GetRateFromExchangeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_usdt_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetRateFromExchangeResponse.ProtoReflect.Descriptor instead.
func (*GetRateFromExchangeResponse) Descriptor() ([]byte, []int) {
	return file_usdt_proto_rawDescGZIP(), []int{1}
}

func (x *GetRateFromExchangeResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *GetRateFromExchangeResponse) GetAsk() float32 {
	if x != nil {
		return x.Ask
	}
	return 0
}

func (x *GetRateFromExchangeResponse) GetBid() float32 {
	if x != nil {
		return x.Bid
	}
	return 0
}

func (x *GetRateFromExchangeResponse) GetAskAmount() float32 {
	if x != nil {
		return x.AskAmount
	}
	return 0
}

func (x *GetRateFromExchangeResponse) GetBidAmount() float32 {
	if x != nil {
		return x.BidAmount
	}
	return 0
}

func (x *GetRateFromExchangeResponse) GetTimestamp() string {
	if x != nil {
		return x.Timestamp
	}
	return ""
}

var File_usdt_proto protoreflect.FileDescriptor

var file_usdt_proto_rawDesc = []byte{
	0x0a, 0x0a, 0x75, 0x73, 0x64, 0x74, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x04, 0x75, 0x73,
	0x64, 0x74, 0x22, 0x1c, 0x0a, 0x1a, 0x47, 0x65, 0x74, 0x52, 0x61, 0x74, 0x65, 0x46, 0x72, 0x6f,
	0x6d, 0x45, 0x78, 0x63, 0x68, 0x61, 0x6e, 0x67, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x22, 0xb7, 0x01, 0x0a, 0x1b, 0x47, 0x65, 0x74, 0x52, 0x61, 0x74, 0x65, 0x46, 0x72, 0x6f, 0x6d,
	0x45, 0x78, 0x63, 0x68, 0x61, 0x6e, 0x67, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65,
	0x12, 0x18, 0x0a, 0x07, 0x73, 0x75, 0x63, 0x63, 0x65, 0x73, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x08, 0x52, 0x07, 0x73, 0x75, 0x63, 0x63, 0x65, 0x73, 0x73, 0x12, 0x10, 0x0a, 0x03, 0x61, 0x73,
	0x6b, 0x18, 0x02, 0x20, 0x01, 0x28, 0x02, 0x52, 0x03, 0x61, 0x73, 0x6b, 0x12, 0x10, 0x0a, 0x03,
	0x62, 0x69, 0x64, 0x18, 0x03, 0x20, 0x01, 0x28, 0x02, 0x52, 0x03, 0x62, 0x69, 0x64, 0x12, 0x1d,
	0x0a, 0x0a, 0x61, 0x73, 0x6b, 0x5f, 0x61, 0x6d, 0x6f, 0x75, 0x6e, 0x74, 0x18, 0x04, 0x20, 0x01,
	0x28, 0x02, 0x52, 0x09, 0x61, 0x73, 0x6b, 0x41, 0x6d, 0x6f, 0x75, 0x6e, 0x74, 0x12, 0x1d, 0x0a,
	0x0a, 0x62, 0x69, 0x64, 0x5f, 0x61, 0x6d, 0x6f, 0x75, 0x6e, 0x74, 0x18, 0x05, 0x20, 0x01, 0x28,
	0x02, 0x52, 0x09, 0x62, 0x69, 0x64, 0x41, 0x6d, 0x6f, 0x75, 0x6e, 0x74, 0x12, 0x1c, 0x0a, 0x09,
	0x74, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x18, 0x06, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x09, 0x74, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x32, 0x69, 0x0a, 0x0b, 0x52, 0x61,
	0x74, 0x65, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x5a, 0x0a, 0x13, 0x47, 0x65, 0x74,
	0x52, 0x61, 0x74, 0x65, 0x46, 0x72, 0x6f, 0x6d, 0x45, 0x78, 0x63, 0x68, 0x61, 0x6e, 0x67, 0x65,
	0x12, 0x20, 0x2e, 0x75, 0x73, 0x64, 0x74, 0x2e, 0x47, 0x65, 0x74, 0x52, 0x61, 0x74, 0x65, 0x46,
	0x72, 0x6f, 0x6d, 0x45, 0x78, 0x63, 0x68, 0x61, 0x6e, 0x67, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x1a, 0x21, 0x2e, 0x75, 0x73, 0x64, 0x74, 0x2e, 0x47, 0x65, 0x74, 0x52, 0x61, 0x74,
	0x65, 0x46, 0x72, 0x6f, 0x6d, 0x45, 0x78, 0x63, 0x68, 0x61, 0x6e, 0x67, 0x65, 0x52, 0x65, 0x73,
	0x70, 0x6f, 0x6e, 0x73, 0x65, 0x42, 0x14, 0x5a, 0x12, 0x67, 0x52, 0x50, 0x43, 0x2d, 0x55, 0x53,
	0x44, 0x54, 0x2f, 0x61, 0x70, 0x69, 0x3b, 0x75, 0x73, 0x64, 0x74, 0x62, 0x06, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x33,
}

var (
	file_usdt_proto_rawDescOnce sync.Once
	file_usdt_proto_rawDescData = file_usdt_proto_rawDesc
)

func file_usdt_proto_rawDescGZIP() []byte {
	file_usdt_proto_rawDescOnce.Do(func() {
		file_usdt_proto_rawDescData = protoimpl.X.CompressGZIP(file_usdt_proto_rawDescData)
	})
	return file_usdt_proto_rawDescData
}

var file_usdt_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_usdt_proto_goTypes = []any{
	(*GetRateFromExchangeRequest)(nil),  // 0: usdt.GetRateFromExchangeRequest
	(*GetRateFromExchangeResponse)(nil), // 1: usdt.GetRateFromExchangeResponse
}
var file_usdt_proto_depIdxs = []int32{
	0, // 0: usdt.RateService.GetRateFromExchange:input_type -> usdt.GetRateFromExchangeRequest
	1, // 1: usdt.RateService.GetRateFromExchange:output_type -> usdt.GetRateFromExchangeResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_usdt_proto_init() }
func file_usdt_proto_init() {
	if File_usdt_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_usdt_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_usdt_proto_goTypes,
		DependencyIndexes: file_usdt_proto_depIdxs,
		MessageInfos:      file_usdt_proto_msgTypes,
	}.Build()
	File_usdt_proto = out.File
	file_usdt_proto_rawDesc = nil
	file_usdt_proto_goTypes = nil
	file_usdt_proto_depIdxs = nil
}
